### ISSUE TITLE
Question (not a bug) : how to deal better with footnotes ? (is: any plan to integrate a wysiwyg-distraction-free editor ?)

### ISSUE THREAD

**Issue by Karmak23** [melmothx/amusewiki#111]
Hi Marco !

I'm quite a fan of amusewiki (used on our website cocoliv.es), but I'm strugling with article editing, especially footnotes.

- Our articles are quite big, and have a lot of footnotes (see [this](https://cocoliv.es/library/notre-opinion-sur-la-campagne-des-insoumis)). Big articles are not so readable in the textarea, even turned bigger with preferences. A distraction free editor (like pyroom on linux).
- besides that, footnotes numbering is problematic in our process of writing articles : we re-read/proof-read articles multiple times, and we add new footnotes upon each re-read, we need to renumber them very often. Idem, as we can reorder sections, footnotes needs to be renumbered.

We tried to edit the articles in external editors (web, like etherpad, local, like gedit) for multi-hand editing. We ended up in multi-window Atom, one open on current location, one open on footnotes, but we still need to re-read everything with search-and-replace when renumbering.

I know I can number footnotes and put them at the end of document in any random order, but when doing this, in final documents they stay random-numbered, which seems confusing / awkward from a traditional book reader point of view. 

In the process of trying to address both of these issues, do you have any plan to integrate some kind of distraction-free editor, like a customized full-screen medium-like JS solution ?

This could help having *inline* footnotes (like in Lyx), where numbering doesn't matter and is generated automatically at submit / publish time, and ease editing of big articles, with distraction free and (very simplified, due to the small set of amuse markup) wysiwyg mode.

I've come across :

- https://github.com/tholman/zenpen (http://www.zenpen.io/)
- https://yabwe.github.io/medium-editor/demo.html (at first sight, seems extendable enough to acheive full amuse syntax with minimum of hacking)
- https://github.com/mduvall/grande.js (demo not currently accessible)
- http://wysiwygjs.github.io/

a list of other alternatives [can be found on S.O](http://stackoverflow.com/questions/6756407/what-contenteditable-editors-are-there).

Any thoughts ? remarks ? Your point-of-view on this issues ? How do you (or other users) deal with these issues ?

Thanks for reading and sorry to post here instead of IRC. I'm asynchronously connected to the internet and prefer discussing here.

**Comment by melmothx** [comment]
Olivier Cortès <notifications@github.com> writes:

> Hi Marco !
>
> I'm quite a fan of amusewiki (used on our website cocoliv.es), but I'm strugling with article editing, especially footnotes.
>
> - Our articles are quite big, and have a lot of footnotes (see [this](https://cocoliv.es/library/notre-opinion-sur-la-campagne-des-insoumis)). Big articles are not so readable in the textarea, even turned bigger with preferences. A distraction free editor (like pyroom on linux).
> - besides that, footnotes numbering is problematic in our process of writing articles : we re-read/proof-read articles multiple times, and we add new footnotes upon each re-read, we need to renumber them very often. Idem, as we can reorder sections, footnotes needs to be renumbered.
>
> We tried to edit the articles in external editors (web, like etherpad, local, like gedit) for multi-hand editing. We ended up in multi-window Atom, one open on current location, one open on footnotes, but we still need to re-read everything with search-and-replace when renumbering.
>
> I know I can number footnotes and put them at the end of document in any random order, but when doing this, in final documents they stay random-numbered, which seems confusing / awkward from a traditional book reader point of view. 

Hi Olivier and thanks for your remarks.

Usually when working on texts with a lot of footnotes which needs
editing, I keep the paragraph and the footnote together, and I
simply number them [1].

E.g.

** Chapter

My paragraph [1] and text [1]

[1] Footnote

[1] Footnote

Here another paragraph [1]

[1] Another footnote.

Then in the editing window, on saving/preview I use the option:
Rearrange the footnotes (under Filters). Which, btw, would break the
text you posted, because there the numbering counts, not the order.

This way only the order matters, and the engine takes care of the
(re)numbering.

Also, this way you can move paragraphs and chapters around without
caring about numbering, as long as you carry the footnotes with you.

This is very close (not exactly there) to the inline footnote feature
you're proposing. Just instead of be inlined, they are in the next
paragraph. And works right away, without waiting for my coding and
finding out another markup syntax which is not horrid.

My concern (from an implementation point of view) is how to deal with a
mixed style of inline/paragraph, which would probably require some
rewriting in the parser. This is for sure doable but still needs to be
done.

https://github.com/melmothx/text-amuse/issues/15

But please first let me know if the approach described above could work
for you.

> In the process of trying to address both of these issues, do you have any plan to integrate some kind of distraction-free editor, like a customized full-screen medium-like JS solution ?
>
> This could help having *inline* footnotes (like in Lyx), where numbering doesn't matter and is generated automatically at submit / publish time, and ease editing of big articles, with distraction free and (very simplified, due to the small set of amuse markup) wysiwyg mode.
>
> I've come across :
>
> - https://github.com/tholman/zenpen (http://www.zenpen.io/)
> - https://yabwe.github.io/medium-editor/demo.html (at first sight, seems extendable enough to acheive full amuse syntax with minimum of hacking)
> - https://github.com/mduvall/grande.js (demo not currently accessible)
> - http://wysiwygjs.github.io/
>
> a list of other alternatives [can be found on S.O](http://stackoverflow.com/questions/6756407/what-contenteditable-editors-are-there).

Well, one of those could very well replace the minimal editor provided
in the editing page. When dealing with something else than a trivial
editing I usually work offline and push to git. I need to try them out
and see what happens, even if I'm not too optimist.

The problem, from what I see, is that, to be the real deal, it needs a
full parser (for both displaying and updating)., 

Unless what we're talking here is only the distraction-free aspect of
the editing (no the wysiwyg thing, which has the parser problem). Then
the problem has another dimension.

> Any thoughts ? remarks ? Your point-of-view on this issues ? How do you (or other users) deal with these issues ?
>
> Thanks for reading and sorry to post here instead of IRC. I'm asynchronously connected to the internet and prefer discussing here.

No problem at all.

Please let me know what do you think.


-- 
Marco

**Comment by Karmak23** [comment]
FANTASTIC (for footnotes, order matters, etc). This will solve both of my issues, because now any editor will do the job ! I will rewrite my current article, and close the issue if this works as expected.

Thanks a lot !

**Comment by Karmak23** [comment]
Works perfectly. All trouble resolved. Too bad I didn't understand this from reading the docs the first time. 

Thanks again.

**Comment by melmothx** [comment]
I'm very glad you like the solution (which was implemented because of your very same problem). Thanks for the feedback!

**Comment by melmothx** [comment]
Btw, if you have Text::Amuse::Preprocessor installed locally, you can do do the renumbering on the command line using `muse-preprocessor.pl --footnotes --inplace file.muse`

https://metacpan.org/pod/distribution/Text-Amuse-Preprocessor/bin/muse-preprocessor.pl
