### ISSUE TITLE
Wordpress Any way to integrate the preamble-container in a wordpress blog ?

### ISSUE THREAD

**Issue by yodatak** [melmothx/amusewiki#154]
I want to integrate in a blog the preamble-container to make it easy to download some text in pdf , and epub of text any idea who to do this

**Comment by melmothx** [comment]
yodatak <notifications@github.com> writes:

> I want to integrate in a blog the preamble-container to make it easy
> to download some text in pdf , and epub of text any idea who to do
> this

I will provide a .json endpoint and some example javascript to fetch
that in the next release. Sounds good?

-- 
Marco

**Comment by melmothx** [comment]
Actually, probably it's better to provide an /embed link which you could load in an iframe. Now, depends how much locked down your WP installation and if it allows iframes at all.

**Comment by melmothx** [comment]
See if such link to use in an `<iframe>` solves the problem for you: https://staging.amusewiki.org/library/amw-version-20/embed

**Comment by yodatak** [comment]
I try with avanced iframe plugin , and its works ! Another question is there is a way to by click on a button to send a wordpress post text and give them a epub , pdf and so one ? Or is it too complicated ? Like give a page to the wiki then dynamicly convert to amuse markdown then provide epub and pdf ? Thanks for the work you done !

**Comment by melmothx** [comment]
yodatak <notifications@github.com> writes:

> I try with avanced iframe plugin , and its works ! Another question is
> there is a way to by click on a button to send a wordpress post text
> and give them a epub , pdf and so one ? Or is it too complicated ?
> Like give a page to the wiki then dynamicly convert to amuse markdown
> then provide epub and pdf ? Thanks for the work you done !

From the amusewiki point of view, this is totally doable. It would be
something like POSTing to an url the parameters with the HTML text and
the various attributes like title/subtitle, together with __username and
__password, create the revision and schedule its publishing, returning
the (expected) text url. It would not appear right away (because of the
async publishing), but shortly enough and will work just fine.

The heavy lifting here is on the WP side. I.e., you would need a
full-feature plugin to store username, password, amw endpoint, then
fetch the post info, do the posting, check if there is an error, and
finally append the <iframe> to the text. There had been in the past
experiments with this, but I'm pretty sure that the code is lost
forever.

Please open a separate issue for this and let me know if you (or someone
else) can and want to work on the WP plugin.

Closing this issue, the code will be rolled out in the next release (due
over the weekend unless there are bad surprises).

-- 
Marco
