### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by xakdeveloper** [melmothx/amusewiki#201]
Hi ,
Thanks for such a productive version of wiki. I have two questions:
1- What kind of changes in po files is needed to make the rep RTL (right to left) friendly ?
2- Does bookbuilder Model/plugins can be used in MediaWiki ?
Thanks,
Xak

**Comment by melmothx** [comment]
Xak Developer <notifications@github.com> writes:

> Hi ,
> Thanks for such a productive version of wiki. I have two questions:

Hello and thanks for your interest.

> 1- What kind of changes in po files is needed to make the rep RTL (right to left) friendly ?

Unfortunately the issue is very much deeper and not localized to the PO
files.

I did some experiments in the past with a RTL language, but didn't go
much far. However, these should be the steps

 - Add a syntax to the Muse markup to handle switching between RTL and
   LTR. IIRC, the main problem was when you mix the two things, e.g.
   English titles in Arabic text. Probably some <rtl> <ltr> tag will do.
   IIRC there is some Unicode character which does the same thing. All
   this should be investigated and implemented in Text::Amuse

 - Add support in the LaTeX and HTML templates, testing. This could turn
   out to be non-trivial (but not impossible, I believe).
   This should be done in Text::Amuse::Compile

 - Finally, add the relevant PO, which shouldn't be a problem in itself,
   and check out how the thing works and looks.

This is for sure very interesting, but also it could be very slow, as I
know virtually nothing about such languages.

What you can do, if you feel inclined:

 - Provide a sample document, in your RTL language of choice, in Muse
   markup (https://amusewiki.org/library/manual) with a sample for each
   syntax rule (quotes, headers, lists, links, footnotes, images,
   tables, captions, etc.), and a rendered PDF with the same text which
   I can use as reference. All this with lenghty, real-life pieces of
   texts and numbers, and with inserts in English where the direction
   switches. This is a small task in itself but without this nothing can
   be done. This would better than having to ask for advise every time I
   work on the code.

 - A PO file is premature, but I wouldn't throw it away of course. But
   still it would be a wasted effort without the above steps.

 - Be patient. Very much depends on my free time, which is currently not
   much. I can't honestly estimate how much it would take.

> 2- Does bookbuilder Model/plugins can be used in MediaWiki ?

The two systems have no relation whatsoever, so no. MediaWiki has its
own bookbuilder (with not so many options), though.

Best wishes

--
Marco

**Comment by xakdeveloper** [comment]
Thank you very much for detailed response, I will try rtl suggestion.

**Comment by melmothx** [comment]
Please keep it open as contains useful information for the future.

**Comment by xakdeveloper** [comment]
ok, thanks

**Comment by melmothx** [comment]
For CSS: https://github.com/ded/R2

**Comment by melmothx** [comment]
I believe that the parser/compiler is now capable to handle RTL. @xakdeveloper If you are still game, please attach a sample text.

**Comment by melmothx** [comment]
PO files for arabic, hebrew, farsi are up for taking.
