### ISSUE TITLE
Use Debian boxes instead of Bento ones

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#275]
https://github.com/melmothx/amusewiki/blob/403baa452f7411c49cbfe576896df58782082ab5/Vagrantfile#L6

Boxes build by Debian people can be found here: https://app.vagrantup.com/debian

**Comment by melmothx** [comment]
@racke Thanks for the hint.

@link2xt what do you think?

**Comment by link2xt** [comment]
I am going to try `debian/contrib-stretch64`. I have opened an issue https://github.com/chef/bento/issues/1179 and Bento boxes are going to build Debian 9.8 too: https://github.com/chef/bento/commit/f8921ab99c405be521a46196fe3f77f29b6a2b5f

I used Bento because they are mentioned as official in Vagrant documentation. Debian boxes seem to be updated faster and are also "official" (to Debian, not Vagrant).

If contrib box works, we can update the box and remove APT vulnerability workarounds. Then maybe switch to free versions and use rsync method for shared folder. It is less convenient for development, but solves timestamp problems that tests still sometimes have.

**Comment by racke** [comment]
Sorry, it looks to me as it just recommends bento - but in a context with Ubuntu. At least when I follow the link in the Vagrantfile. So why are  the Debian boxes less convenient for development?

**Comment by link2xt** [comment]
> So why are the Debian boxes less convenient for development?

See https://app.vagrantup.com/debian: "The default boxes only include software from the Debian main archive and use either rsync or bind mounts for shared folder functionality." `contrib-*` versions also support vboxfs, they are probably ok.
