### ISSUE TITLE
Permalinks for sections

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#28]
Currently links for sections have a target like #toc22, which isn't suitable to pass around or refer to as the section structure can change.

Can we have permalinks instead like #section-title-foo-bar ?

**Comment by melmothx** [comment]
Well, even if this schema could be more stable, section structure can
change nevertheless, because of section renaming and such. Also
section titles are not guaranteed to be unique. It's very common to
have chapters and sections with just numbering, so the schema could be
chapter-section-title, if chapter level exists. But, again, no
guaratee that it's unique.

The current #toc22 is more robust against typos in the section titles,
and guaranteed to be unique. Of course if you add stuff in the middle,
the thing breaks, but if you just append, it's safe.

So, unclear if there is a real gain here (worth of facing eventual
problems which I'm pretty sure will pop up with new code).

Keeping open for now, anyway.

**Comment by melmothx** [comment]
Also, this relates to an old bug (which still is hanging there), where
linking pages by fragment, is going to do a weird jump (because of the
fixed navbar on the top). Internal jumping is worked around via some
JS, but direct linking is going to have the heading hidden by the
topbar.

On the other hand, the fixed navbar has the upside to give access to
the ToC at any point (and this is very good for mobiles).

So, situation right now is that having permalinks to fragments is not
really a good idea. Unless something else change, of course.

**Comment by melmothx** [comment]
As per the comment above, the gains for such a change, which has also raises backcompatibility, are very much questionable. Closing this issue, as it doesn't have a clean solution.
