### ISSUE TITLE
proofreading the interface

### ISSUE THREAD

**Issue by mouseb** [melmothx/amusewiki#315]
marco, i also wonder if i cdnt proofread the interface for you as i explore the software? i have already noticed a number of minors things that cd be fixed up. (i work as a professionally as a translator and english language proofreader.)

the only thing is i don't know how to set up a dev env to make proposed edits that way, as i'm not a coder.

**Comment by melmothx** [comment]
mouseb <notifications@github.com> writes:

> marco, i also wonder if i cdnt proofread the interface for you as i
> explore the software? i have already noticed a number of minors things
> that cd be fixed up. (i work as a professionally as a translator and
> english language proofreader.)

It would be very welcome and of course I thank you in advance!

> the only thing is i don't know how to set up a dev env to make
> proposed edits that way, as i'm not a coder.

This should help:

https://amusewiki.org/library/hacking

which also points to the template directory where the changes should
happen.

Another solution (probably the most viable), would be to correct the
string in the English PO file, so this
https://amusewiki.org/library/translating-the-interface#toc3 should
help.

Considering the large amount of translations already in place, it could
be disrupting to have the source strings corrected (because the changes
should then propagated).

At some point the changes should be propagated but this way you have a
straightforward way to contribute without messing with the code.

Cheers

--
Marco

**Comment by mouseb** [comment]
hi m, i setup poedit on my end. if thats ok w you ill make an updated/edits file then send on in a while, or mayb i cd send on if you were planning an update. i'm actually not sure you'll need to propagage much, it is mostly just tweaking things for expression. the meaning is almost the same.

**Comment by melmothx** [comment]
@mouseb yes, please use the `en.po` file and send it (or open a pull request, as you prefer).

**Comment by melmothx** [comment]
@mouseb Received and imported in 6948ce88. Closing this, thanks
