### ISSUE TITLE
URL Slug for Single Quotes

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#392]
The amuse wiki converts quotes to "-" when createing url slug.

like:
`Emma Goldman'ın Hayatı`
to:
`emma-goldman-in-hayati`

But is wrong for Turkish, in our language we are often use quotes to separate noun suffixes, converting quotes to hyphens in kebab URLs is annoying.

we would like to see this:
`emma-goldmanin-hayati`

Can URL conversion rules be changed without accessing the server?

**Comment by melmothx** [comment]
Rojen Zaman ***@***.***> writes:

> The amuse wiki converts quotes to "-" when createing url slug.
>
> like:
> `Emma Goldman'ın Hayatı`
> to:
> `emma-goldman-in-hayati`
>
> But is wrong for Turkish, in our language we are often use quotes to
> separate noun suffixes, converting quotes to hyphens in kebab URLs is
> annoying.
>
> we would like to see this:
> `emma-goldmanin-hayati`
>
> Can URL conversion rules be changed without accessing the server?

Well, first and foremost, the URI conversion is always an approximation.
For some languages it's even plainly wrong (for example Japanese) and
not easily amendable. However, it's not gratuitous, because this way
there a 1:1 correspondence between the file on the disk and the URI (and
a lot of is built around this design).

So, there's a new option and an existing, but still relatively new,
option:

 1. "On text creation, enforce user to choose the URI" this was added on
     master today and will be available in the next release.

 2. Allow Unicode URIs for categories (author, topics).

Both have the effect to let the user choose the text URI upon creation,
with an on-the-fly check which should make it easy (but the second
option has other effects, as the label says).

If you think that the current way the URI is automatically composed is
not good enough, you're going to have the option to choose it manually
and that should do it.

Now, in theory there could be a language specific way to asciify the
URI, but I'm wondering if it's doable or wise. For example, there could
be cases where you would want the hyphen instead, and not just stripped
out, so I'm leaning toward the manual way.

Thoughts?

-- 
Marco

**Comment by rojenzaman** [comment]
> Now, in theory there could be a language specific way to asciify the
> URI, but I'm wondering if it's doable or wise. For example, there could
> be cases where you would want the hyphen instead, and not just stripped
> out, so I'm leaning toward the manual way.

> Thoughts?

There may be scenarios where both situations occur. You are right. It is a complicated situation. If the language-specific asciiization option is not possible, I think the following two features should be added:

  1. Suggested converted URI: I think it is necessary to add a pre-made converted URI to the URI select box so that anyone who is satisfied or dissatisfied with the URI has a chance to play with it.
 
  2. Changing the URI after the text is created: What do we do if we are not satisfied with the URI of the previously generated text? In the current case it is necessary to create a new text and redirect the old text to the new URI. It's a pretty tough road. Could users be given the ability to change the URI of the created text instead? The old URI can then be arbitrarily redirected to the new URI.

**Comment by melmothx** [comment]
Rojen Zaman ***@***.***> writes:

>> Now, in theory there could be a language specific way to asciify the
>> URI, but I'm wondering if it's doable or wise. For example, there could
>> be cases where you would want the hyphen instead, and not just stripped
>> out, so I'm leaning toward the manual way.
>
>> Thoughts?
>
> There may be scenarios where both situations occur. You are right. It
> is a complicated situation. If the language-specific asciiization
> option is not possible, I think the following two features should be
> added:
>
>   1. Suggested converted URI: I think it is necessary to add a
>   pre-made converted URI to the URI select box so that anyone who is
>   satisfied or dissatisfied with the URI has a chance to play with it.

I think it's doable, yes.

>   2. Changing the URI after the text is created: What do we do if we
>   are not satisfied with the URI of the previously generated text? In
>   the current case it is necessary to create a new text and redirect
>   the old text to the new URI. It's a pretty tough road. Could users
>   be given the ability to change the URI of the created text instead?
>   The old URI can then be arbitrarily redirected to the new URI.

Honestly, I'm not a big fan of such renaming, but the same "tough road"
can be automated, yes.

-- 
Marco

**Comment by rojenzaman** [comment]
Thanks a lot for considering all of those!

**Comment by melmothx** [comment]
@rojenzaman For the first feature, please give it a try here: https://staging.amusewiki.org/action/text/new

**Comment by rojenzaman** [comment]
I have tried it works pretty.
