### ISSUE TITLE
"@" character at URLs

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#395]
Amusewiki converts "@" sign to "%40".
URLs containing "%40" do not follow links correctly.
For example all  mastodon user URLs are failing.

Example: https://staging.amusewiki.org/library/mastodon-url-en

**Comment by melmothx** [comment]
Rojen Zaman ***@***.***> writes:

> Amusewiki converts "@" signt to "%40". 
> URLs containing "%40" do not follow links correctly.
> For example all  mastodon user URLs are failing.
>
> Example: https://staging.amusewiki.org/library/mastodon-url-en

Well, let's start with saying that it has been this way for at least a
decade by now. I think it's not really clear to me, looking at:

https://datatracker.ietf.org/doc/html/rfc3986#page-12
https://en.wikipedia.org/wiki/Percent-encoding
https://developers.google.com/maps/url-encoding

Because the @ there seems used as a literal @, not with a special
meaning (the same way a slash would be a path separator).

Hence the "urls are failing" thing could be depending on the mastondon's
server implementation.

If you are in an hurry, you can still add a bit of js in the local.js to
replace %40 into @ in urls.

$('a').each(function() { var link = $(this).attr('href'); if (link) { $(this).attr('href', link.replace('%40', '@')) } });

-- 
Marco

**Comment by rojenzaman** [comment]
> $('a').each(function() { var link = $(this).attr('href'); if (link) { $(this).attr('href', link.replace('%40', '@')) } });

Thanks for help and informations. I will applied that.
