### ISSUE TITLE
Directive autofill on the new text page enforces semicolon even comma is used.

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#420]
Before the last update, when a directive was added (e.g. category form) the comma was automatically placed next to the directive, but after the last update (2,560) it was converted to the semicolon. This can create problems in the context of backward compatibility (e.g. running script inside archive). 

Is there a way to revert it back to when it was a comma? Or was there a reason for this to convert from comma to semicolon?

**Comment by melmothx** [comment]
This indeed change in 944478bb6 because the semicolon has higher priority as a separator and it's always considered a separator, while the comma is allowed in category names. That didn't change and it's been this way basically forever. So this change makes the suggestion more robust.

Your scripts should use the semicolon as separator if present in the script, falling back to comma if not so.

**Comment by melmothx** [comment]
Ok, I see the help string says otherwise. Bit of a mess. I guess we revert to the comma, yes.
