### ISSUE TITLE
<example> doesn't interpolate within lists

### ISSUE THREAD

**Issue by racke** [melmothx/amusewiki#91]
E.g.:

```
 1. Create unix user and set password
    <example>
    useradd -c "My Email" -s /bin/false mymail
    passwd mymail
    </example>
```

**Comment by melmothx** [comment]
All tagged blocks don't play with lists.

Beside the implementation details (being the list code the most twisted because
of nesting, false positives, etc.), the input would look confusing, because, as
per manual, the tags need to be put on a line by themself at column 0. Which is
impossible in lists. The assumption here is that when you start a tagged block,
you break out of the list.

Also, the layout is not going to be good, being the code blocks (because of
lack of wrapping) already complicated by itself and prone to break when the
page width shrinks. Go figure when the list indentation steals real estate.

However, in this specific case

```
 1. Create unix user and set password:

    =useradd ....mymail=

    =passwd mymail=

```

will do the job just fine.
